// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXpeBmcmLSTiX4RVQRo6Ov6iDPFRWlCUk',
    appId: '1:1044639972810:web:5dcc430f0fb2946470e333',
    messagingSenderId: '1044639972810',
    projectId: 'baylo-ecommerce-app',
    authDomain: 'baylo-ecommerce-app.firebaseapp.com',
    storageBucket: 'baylo-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlrJUesnmbh9d2s61lR_x0KpUjqT1Mgvs',
    appId: '1:1044639972810:android:e36688542f0e32a370e333',
    messagingSenderId: '1044639972810',
    projectId: 'baylo-ecommerce-app',
    storageBucket: 'baylo-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJUJDc50kJyYQ9RUNVpv_y1lUXZ3VT6No',
    appId: '1:1044639972810:ios:c547afba9585b80e70e333',
    messagingSenderId: '1044639972810',
    projectId: 'baylo-ecommerce-app',
    storageBucket: 'baylo-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.myEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJUJDc50kJyYQ9RUNVpv_y1lUXZ3VT6No',
    appId: '1:1044639972810:ios:0067d736c1e069b170e333',
    messagingSenderId: '1044639972810',
    projectId: 'baylo-ecommerce-app',
    storageBucket: 'baylo-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.myEcommerce.RunnerTests',
  );
}
